### ISSUE TITLE
Use bash instead of Sh for AWS jobs

### ISSUE THREAD

**Issue by smondet** [hammerlab/coclobas#119]
See

```ocaml
  let cmd = ["sh"; script_path ] in
```

https://github.com/hammerlab/coclobas/blob/503fc5b23bceee4f5368beaf1b4de16f534346c7/src/ketrew_backend/plugin.ml#L94

while at least Biokepi jobs contain some bashisms (e.g. `set -o pipefail`)

**Comment by armish** [comment]
Yes, please! The following ugly thing was my work around the issue to not be the person who suggested the change :)
https://github.com/hammerlab/biokepi/pull/468/commits/47076fd6ff56bdf24d3ce0380ab2ff4df6bf21ae

I actually didn't know we were using `sh` by default and had some fun time debugging why the `kserver` was always reporting failure when I used this as part of an evaluated target condition:
https://github.com/hammerlab/biokepi/blob/master/src/environment_setup/conda.ml#L122

Turns out, `sh` doesn't know what `source` and it was using `.` before `source` was cool :man_shrugging:

**Comment by smondet** [comment]
@armish but this is just for AWS, on kubernetes it's already `bash`: https://github.com/hammerlab/coclobas/blob/master/src/ketrew_backend/plugin.ml#L60
?

**Comment by armish** [comment]
Yep - that is right, but that setting still doesn't bind the kserver and command-based conditions still go through our old friend `sh`, which was because of a very specific use case. Can't rule out the possibility that I did something stupid with my configuration at some point in time and now suffering the consequences, but yeah - the workers till get their shiny `bash` but the good old server uses `sh` for checking conditions.

Can demo that to you tomorrow - would be great to have another pair of eyes as I do get easily and sometimes in the world modules and end up with wrong answers. In any case, nothing really serious - was just a funny but really educating experience for me.

**Comment by smondet** [comment]
This is fixed; I referenced #19 instead of #119 in the commit message :/
